CREATE ROLE feathertrend WITH LOGIN PASSWORD 'PZBv$LeUA@LzpH6a&rj@';

CREATE DATABASE feathertrend
    OWNER    = feathertrend
    ENCODING = 'UTF8';

GRANT ALL PRIVILEGES ON DATABASE feathertrend TO feathertrend;

\connect feathertrend

ALTER SCHEMA public OWNER TO feathertrend;
GRANT ALL ON SCHEMA public TO feathertrend;

CREATE TABLE species (
    id              INTEGER                NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    scientific_name CHARACTER VARYING(255) NOT NULL,
    common_name     CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT species_pkey PRIMARY KEY (id)
);

CREATE TABLE pictures (
    id          INTEGER                         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    datetime    TIMESTAMP(0) WITHOUT TIME ZONE  DEFAULT NULL,
    path        CHARACTER VARYING(8191)          NOT NULL,
    species_id  INTEGER,
    CONSTRAINT pictures_pkey          PRIMARY KEY (id),
    CONSTRAINT pictures_species_id_fk FOREIGN KEY (species_id)
        REFERENCES public.species (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE users (
    id       INTEGER                NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email    CHARACTER VARYING(180) NOT NULL,
    roles    JSON                   NOT NULL,
    password CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA public TO feathertrend;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO feathertrend;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON TABLES    TO feathertrend;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON SEQUENCES TO feathertrend;