CREATE ROLE feathertrend_test WITH LOGIN PASSWORD 'password';

CREATE DATABASE feathertrend_test
    OWNER    = feathertrend_test
    ENCODING = 'UTF8';

GRANT ALL PRIVILEGES ON DATABASE feathertrend_test TO feathertrend_test;

\connect feathertrend_test

ALTER SCHEMA public OWNER TO feathertrend_test;
GRANT ALL ON SCHEMA public TO feathertrend_test;

CREATE TABLE species (
    id              INTEGER                NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    scientific_name CHARACTER VARYING(255) NOT NULL,
    common_name     CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT species_pkey PRIMARY KEY (id)
);

CREATE TABLE pictures (
    id          INTEGER                         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    datetime    TIMESTAMP(0) WITHOUT TIME ZONE  DEFAULT NULL,
    path        CHARACTER VARYING(8191)          NOT NULL,
    species_id  INTEGER,
    CONSTRAINT pictures_pkey          PRIMARY KEY (id),
    CONSTRAINT pictures_species_id_fk FOREIGN KEY (species_id)
        REFERENCES public.species (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE users (
    id       INTEGER                NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email    CHARACTER VARYING(180) NOT NULL,
    roles    JSON                   NOT NULL,
    password CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA public TO feathertrend_test;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO feathertrend_test;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON TABLES    TO feathertrend_test;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON SEQUENCES TO feathertrend_test;